name: Build plugin

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: dist

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Build
        id: build
        run: |
          npm install
          npm run build
          mkdir -p ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          echo "tag_name=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            main.js
            manifest.json
